// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_FolderWatcher.cpp"
#include "UVLADIE3JM/moc_LiveLink.cpp"
#include "UVLADIE3JM/moc_SessionStore.cpp"
#include "UVLADIE3JM/moc_VipsEngine.cpp"
#include "UVLADIE3JM/moc_XylodLink.cpp"
